In [39]:
import numpy as np
row1 = int(input("Enter number of rows: "))
col1= int(input("Enter number of columns: "))
matrix1 = []
print(f"Enter {row1 * col1} elements row by row:")
for i in range(row1):
    row1=[]
    for j in range(col1) :
     val=int(input("Enter elements:"))
     row1.append(val)
    matrix1.append(row1)
row2 = int(input("Enter number of rows: "))
col2= int(input("Enter number of columns: "))
matrix2 = []
print(f"Enter {row2 * col2} elements row by row:")
for i in range(row2):
    row2=[]
    for j in range(col2) :
     val1=int(input("Enter elements:"))
     row2.append(val1)
    matrix2.append(row2)
a=np.array(matrix1)
print("first matrix is : ",a)
a1=np.array(matrix2)
print("Second matrix : ",a1)
# print("The dot product is :")
# print(np.dot(a,a1))
# print("Transpose of 1st one :")
# print(np.transpose(a))
# print("Transpose of 2nd one :")
# print(np.transpose(a1))
# print("Trace of first matrix :")
# print(np.trace(a))
# print("Trace of second matrix :")
# print(np.trace(a1))
print("Rank of first matrix :")
print(np.linalg.matrix_rank(a))
print("Rank of second matrix :")
print(np.linalg.matrix_rank(a1))
print("Determinant if first matrix : ")
print(np.linalg.det(a))
print("Determinant if second matrix : ")
print(np.linalg.det(a1))
print("Inverse of second matrix : ")
print(np.linalg.inv(a1))
print("Eigen value of matrix one :")
print(np.linalg.eigvals(a))
print("eigen vector of first matrix : ")
print(np.linalg.eig(a))




Enter 9 elements row by row:
Enter 9 elements row by row:
first matrix is :  [[1 2 5]
 [3 7 6]
 [2 3 1]]
Second matrix :  [[8 5 6]
 [4 3 8]
 [2 5 1]]
Rank of first matrix :
3
Rank of second matrix :
3
Determinant if first matrix : 
-17.999999999999996
Determinant if second matrix : 
-152.0
Inverse of second matrix : 
[[ 0.24342105 -0.16447368 -0.14473684]
 [-0.07894737  0.02631579  0.26315789]
 [-0.09210526  0.19736842 -0.02631579]]
Eigen value of matrix one :
[10.62832872  0.72090914 -2.34923787]
eigen vector of first matrix : 
EigResult(eigenvalues=array([10.62832872,  0.72090914, -2.34923787]), eigenvectors=array([[-0.35920583, -0.81111133, -0.80264294],
       [-0.86721875,  0.55726601, -0.11770524],
       [-0.34482287, -0.17763165,  0.58473052]]))
