In [ ]:
import numpy as np

f=np.array([32, 68, 104, 212, 0]) 
c=(f-32)*5/9 
print("Fahrenheit:",f)  
print("Celsius:",c) 


Fahrenheit: [ 32  68 104 212   0]
Celsius: [  0.          20.          40.         100.         -17.77777778]


In [11]:
arr=np.random.randint(0, 1000, size=1000)
print("Array elements are : ",arr)

avg=np.mean(arr)
print("Average is : ",avg)
var=np.var(arr)
print("The variance is : ",var)
std=np.std(arr)
print("The standard deviation is : ",std)


Array elements are :  [268 516 902 613 972 404 375 665 219 648 893 659 495 565 571 761 257 398
 911 635 676 122 569 995 323 517  98 386 285 894 220 666 903 694 603 214
 575 117 329 343 646 109 714 966 869 598 914 115 400 407 631 778 568 565
 530  93 663 654 499 845 963 662 717  47 804  72 894 129  60  62  29 311
 402 264 177 823 432 917  73 729  83 165 152 410  31 813 679 220 984   2
 908 634 286 299 657 919 648 922 316 824 266 858 295 129 701 497 725 692
 576 219 310 505  96 794 641 703 113 339 493 583 713 894 189 853 897 869
 692  32 512 887 979 429 713 921 734 736 952 676 106 446 376 154 887   6
 919  84 183 677 597 561 548 978 316 996 851 501  53 557 405 385 892 905
 882 211 623 985 813 399 300 478 817 988 975 209  72 239 194 233 956 738
 281 590  67 884 425 585 959 288 751 173 128 783 146 223 492 868 186 229
 242 589 297 979 512 599 137 353 764 384 881  29 215 682 285  20 819 593
  22 153 605 678 726 777 885 294 572 572  83 200 333 788 400 374 425 219
 620  23 333 320 483 108 670 

In [28]:
degree=np.array([0,45,90,180,360])
rad=np.deg2rad(degree)
print("The degree array elements are : ",degree)
print("The radius array is : ",rad)

The degree array elements are :  [  0  45  90 180 360]
The radius array is :  [0.         0.78539816 1.57079633 3.14159265 6.28318531]


In [15]:
arr=np.array([15,17,21,8,98])
print("the array elements are : ",arr)
diff=np.diff(arr)
print("The difference in neighbouring elements are : ",diff)


the array elements are :  [15 17 21  8 98]
The difference in neighbouring elements are :  [  2   4 -13  90]


In [ ]:
arr=np.array([12 + 3j, 2+4j,32+5j,21+2j,4+1j,67+9j,2+3j])
sort=np.sort_complex(arr)
print(sort)

[ 2.+3.j  2.+4.j  4.+1.j 12.+3.j 21.+2.j 32.+5.j 67.+9.j]


In [15]:
arr=np.random.randint(1,20,size=10)
print("The array elements are : ",arr)
new=arr[arr>4]
print("elements Greater than 4 : ",new)


The array elements are :  [12  2 18  2 18  3 10 15 17  2]
elements Greater than 4 :  [12 18 18 10 15 17]


In [16]:
import numpy as np
arr=np.random.randint(1,100,size=10)
print("The array elements are : ",arr)
s=int(input("Enter a number you are searching for : "))
x=np.where(arr==s)
if len(x[0])==0:
    print("Element not found")
else:
    print("Number found at position ",*x[0]+1)



The array elements are :  [28 92 90 46 37 91 42 60 79 41]
Number found at position  5


In [3]:
import numpy as np
a=np.arange(30,61,2) 
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]


In [9]:
import numpy as np
arr=np.array([3,4,5,6])
text=np.savetxt("array.txt",arr)
load=np.loadtxt("array.txt")
print("Original array : ",arr)
print("Loaded array : ",load)

Original array :  [3 4 5 6]
Loaded array :  [3. 4. 5. 6.]


In [11]:
arr=np.array([[1,2,3],
              [4,3,1],
              [7,4,2]])
print("The array elements are : ",arr)
sum=np.sum(arr)
print("The sum of all elements is : ",sum)
srow=np.sum(arr,axis=1)
print("sum of each row : ",srow)
scol=np.sum(arr,axis=0)
print("The sum of each column is : ",scol)

The array elements are :  [[1 2 3]
 [4 3 1]
 [7 4 2]]
The sum of all elements is :  27
sum of each row :  [ 6  8 13]
The sum of each column is :  [12  9  6]
