In [ ]:
import numpy as np
#tuple
a=(1,2,3,4)
print(type(a))   #printing type 
p=np.array((1,2,5,6))  #converting tuple to array
print(p)
print(type(p))   
s=[9,8,7,6]  #list
print(type(s))

<class 'tuple'>
[1 2 5 6]
<class 'numpy.ndarray'>
<class 'list'>


In [ ]:

p=np.arange(10) #function to print range of numbers 0 to n-1
print(p)
a=np.arange(2,100,2) #even  numbers
print(a)
b=np.arange(1,99,2) #odd numbers
print(b)
c=np.zeros(2,int) #all elements 0
print(c)
d=np.ones(3,int) #three one4s in array
print(d)
arr=np.ones((3,3),int) #3x3 matrix with all 1
print(arr)
mat=np.array([[1,2,3], #creating our own matrix
             [4,5,6],
             [7,8,9]])
print(mat)
id=np.eye(3) #eye-identity matrix
print(id)
id1=np.identity(3) #using identity function
print(id1)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]
[0 0]
[1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'int'>


In [ ]:

arr=np.arange(1,8) #creating array
print(arr)
print(arr[1:5]) #slicing 1 to 4
print(arr[:5]) #slicing 0 to 4
print(arr[1:]) #starts from 1st index to end
print(arr[-3]) #3rd element from last
print(arr[-4:-1]) #from 4th element from last to 2nd element from last
print(arr[3])
c=arr  #copying traditionally | any changes to the original array will affect c
print(c)
b=np.copy(arr) #copying a to b using function | any changes to the original array will not affect b
print(b)
arr[2]=10
print(arr)
print(b)
print(c)


[1 2 3 4 5 6 7]
[2 3 4 5]
[1 2 3 4 5]
[2 3 4 5 6 7]
5
[4 5 6]
4
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 1  2 10  4  5  6  7]
[1 2 3 4 5 6 7]
[ 1  2 10  4  5  6  7]


In [ ]:

a=[1,2,3,4]
b=[9,8]
c=np.concatenate((a,b)) #concatenate
print(c)


[1 2 3 4 9 8]


In [65]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])
m2=np.array([[9,8,7],[12,13,14],[15,7,6]])
s=np.concatenate((m1,m2),axis=1) #axis - first row 1 st matrix will be concatenated with first row of second matrix and so on
print(s)
print("Without axis :")
r=np.concatenate((m1,m2)) #without using axis
print(r)


[[ 1  2  3  9  8  7]
 [ 4  5  6 12 13 14]
 [ 7  8  9 15  7  6]]
Without axis :
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 9  8  7]
 [12 13 14]
 [15  7  6]]


In [85]:
z=np.arange(4,9)
print(z)
#searching
x=np.where(z==9)
if len(x[0])==0:
    print("Element not found")
else:
    print("Number found at position ",*x[0]+1)


[4 5 6 7 8]
Element not found
